### ISSUE TITLE
[FEATURE] Export automatically for iOS mono version

### ISSUE THREAD

**Issue by gustavottc** [Poing-Studios/Godot-AdMob-Android-iOS#25]

**Comment by gustavottc** [comment]
@brendonion call you tell to me how configure the MacOS for build with mono?

**Comment by gustavottc** [comment]
Is giving me this error: 

Found Mono root directory: /Library/Frameworks/Mono.framework/Versions/Current
Found Mono JIT compiler version: 6.12.0.93
AssertionError: :
  File "/Users/runner/work/Godot-AdMob-Android-iOS/Godot-AdMob-Android-iOS/godot-3.1.2-stable/SConstruct", line 422:
    config.configure(env)
  File "./modules/mono/config.py", line 250:
    make_template_dir(env, mono_root)
  File "./modules/mono/config.py", line 273:
    assert False

**Comment by brendonion** [comment]
Hey I just followed the official Godot tutorial: https://docs.godotengine.org/en/stable/development/compiling/compiling_with_mono.html

You have to clone the specific mono version repo you have https://www.mono-project.com/docs/about-mono/versioning/#mono-source-versioning

You have to clone this repo and run the scripts https://github.com/godotengine/godot-mono-builds

**Comment by gustavottc** [comment]
I really need this godot-mono-builds repository? Because i didnt saw in the official Godot tutorial

And this godot-mono-build will be inside of Godot Source Code?

**Comment by brendonion** [comment]
Oh sorry, that's for the ios/android build templates. If you want to build godot mono for osx, you do the following:
`scons p=osx tools=yes module_mono_enabled=yes mono_glue=no` (generates a <godot_binary>)
`<godot_binary> --generate-mono-glue modules/mono/glue`

and then

`scons p=osx tools=yes module_mono_enabled=yes mono_glue=yes`
`scons p=osx tools=no module_mono_enabled=yes mono_glue=yes`

But for the ios/android templates, you need to clone the `godot-mono-builds` repo outside of the godot repo, and run the commands from inside `godot-mono-builds`. But make sure you also clone the specific mono version repo as well.

**Comment by gustavottc** [comment]
Oh, ok, i will try here but it will may take some time, because i dont have a Mac and iam using the GitHub Actions for that.

In this mid-time you can try to compile by yourself:


https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/blob/e74ad4f668b8f058ffef5cafa6db0dbdbb9c6c42/README.md#ios-v300

**Comment by gustavottc** [comment]
Dont forget to:

https://developers.google.com/admob/ios/ios14#skadnetwork

and 

https://developers.google.com/admob/ios/ios14#request

**Comment by brendonion** [comment]
Okay I'll give it a shot!

**Comment by gustavottc** [comment]
Hey @brendonion im having this error:

Making all in arch
make[4]: Nothing to be done for `all-am'.
Making all in utils
/Applications/Xcode_12.app/Contents/Developer/usr/bin/make  all-recursive
  CC       libmonomath_la-mono-math-c.lo
  CCLD     libmonomath.la
  CC       libmonoutils_la-dlmalloc.lo
  CC       libmonoutils_la-os-event-unix.lo
  CC       libmonoutils_la-mono-md5.lo
  CC       libmonoutils_la-mono-sha1.lo
  CC       libmonoutils_la-mono-logger.lo
  CC       libmonoutils_la-mono-codeman.lo
/Users/runner/work/Godot-AdMob-Android-iOS/Godot-AdMob-Android-iOS/mono/mono/utils/mono-codeman.c:669:3: error: implicit declaration of function 'pthread_jit_write_protect_np' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                pthread_jit_write_protect_np (0);
                ^
/Users/runner/work/Godot-AdMob-Android-iOS/Godot-AdMob-Android-iOS/mono/mono/utils/mono-codeman.c:690:4: error: implicit declaration of function 'pthread_jit_write_protect_np' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        pthread_jit_write_protect_np (1);
                        ^
2 errors generated.
make[5]: *** [libmonoutils_la-mono-codeman.lo] Error 1
make[4]: *** [all-recursive] Error 1
make[3]: *** [all] Error 2
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Running command 'make': make -j1 -C /Users/runner/mono-configs/ios-arm64-release
'make' exited with error code: 2


Please check the code if is missing something: 

https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/actions/runs/364531974/workflow

**Comment by brendonion** [comment]
What command are you running? I believe you have to change the mono repo branch to the specific mono version you are using before running:
```
python3 ./ios.py configure --target=arm64
python3 ./ios.py make --target=arm64
```
Check this table https://www.mono-project.com/docs/about-mono/versioning/#mono-source-versioning.

**Comment by brendonion** [comment]
Yeah I'm just getting so many issues now. I've compiled everything, exported the ios templates, and followed the ios admob steps, but now the game buttons just don't even work. (I also had to change MobileCoreServices -> CoreServices and add PromisesObjc). I'm wondering if it's a mono version mismatch, but essentially the error is:
```
**ERROR**: Method failed. Returning: __null
2020-11-15 10:19:31.994256-0800 app_name[17583:5262887]    At: modules/mono/csharp_script.cpp:2939:can_instance() - Method failed. Returning: __null
```

**Comment by gustavottc** [comment]
did you manage to compile? try to compile without the admob module to see the result

**Comment by brendonion** [comment]
Hmm, yeah I re-compiled the ios templates without the admob module, and same thing. So it must've been a messed up build in the first place.

**Comment by gustavottc** [comment]
@brendonion now yet, is still giving me this error:

https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/runs/1403642388?check_suite_focus=true

**Comment by brendonion** [comment]
Oh man, I have no idea on that one. Maybe due to this issue https://github.com/godotengine/godot-mono-builds/issues/11 ? Maybe try a different mono version? They recommend their CI version here https://github.com/godotengine/godot-mono-builds/issues/9#issuecomment-672242162 (6.8.0.123)

**Comment by gustavottc** [comment]
I created a issue here: https://github.com/godotengine/godot-mono-builds/issues/17, i guess this is something missing in ```godot-mono-builds``` repository

**Comment by brendonion** [comment]
Ok great, let's see where it leads!

**Comment by gustavottc** [comment]
For Android is perfectly working, you can try here: 

https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/releases/tag/Android_mono_v3.2.2%2B

(just versions 3.2.2+)

**Comment by gustavottc** [comment]
These are the commands that i`m using:

        brew install autoconf automake libtool
        export MONO_SOURCE_ROOT=/Users/runner/work/Godot-AdMob-Android-iOS/Godot-AdMob-Android-iOS/mono
        cd godot-mono-builds
        python3 ./patch_mono.py
        python3 ./ios.py configure --target=arm64
        python3 ./ios.py make --target=arm64

**Comment by brendonion** [comment]
Excellent, I'll give that a shot soon 🙌

**Comment by brendonion** [comment]
Also, if you're still working on the iOS builds, make sure you add `mono_glue=yes`. I noticed it wasn't there in the workflows.
```
scons p=iphone tools=no target=release arch=arm module_mono_enabled=true mono_glue=yes mono_prefix="$HOME/mono-installs/ios-arm64-release"
        scons p=iphone tools=no target=release arch=arm64 module_mono_enabled=true mono_glue=yes mono_prefix="$HOME/mono-installs/ios-arm64-release"
```

**Comment by brendonion** [comment]
Also worth noting, iOS Plugins are in the works 💯 
https://github.com/godotengine/godot/pull/41340

**Comment by gustavottc** [comment]
Nice, I think the iOS Plugin will be only available for 3.2.5 or 4.0 version.


I'm still with problems with godot-mono-builds, this is the latest problem:

**Comment by gustavottc** [comment]
Hey @brendonion , i found this on official documentation: https://docs.godotengine.org/en/stable/development/compiling/compiling_with_mono.html#notes

```Do not build your final binaries with mono_glue=no. This disables C# scripting. This option must be used only for the temporary binary that will generate the glue. Godot will print a warning at startup if it was built without the glue sources.```

**Comment by brendonion** [comment]
Oh did you get it working btw? I see the release tag but not the template ❓

**Comment by gustavottc** [comment]
Try to download here: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/suites/1515992304/artifacts/26683307

i`m having some troubles about upload to release tag

**Comment by brendonion** [comment]
Hmm so close! Getting this error now..
```
Run this binary with '--generate-mono-glue path/to/modules/mono/glue'
2020-11-17 08:47:44.142427-0800 godot_app[1049:190092] **ERROR**: Method failed. Returning: __null
```

**Comment by gustavottc** [comment]
This is the same error of this?

> Yeah I'm just getting so many issues now. I've compiled everything, exported the ios templates, and followed the ios admob steps, but now the game buttons just don't even work. (I also had to change MobileCoreServices -> CoreServices and add PromisesObjc). I'm wondering if it's a mono version mismatch, but essentially the error is:
> 
> ```
> **ERROR**: Method failed. Returning: __null
> 2020-11-15 10:19:31.994256-0800 app_name[17583:5262887]    At: modules/mono/csharp_script.cpp:2939:can_instance() - Method failed. Returning: __null
> ```
> 
> Probably due to it not able to even run the C# scripts.

**Comment by brendonion** [comment]
Very similar, this time it's saying: `Run this binary with '--generate-mono-glue path/to/modules/mono/glue'` specifically.

**Comment by gustavottc** [comment]
Do you have Discord? Will be better for chating, i think this error is out of scope of this module but i can help you with it

**Comment by brendonion** [comment]
I'm at work now, but we could chat later today for sure. I'm on PST time btw

**Comment by brendonion** [comment]
But I really think we need that `mono_glue=yes` when running scons, it is what enables C# scripting.

**Comment by gustavottc** [comment]
Yes, you're right: https://docs.godotengine.org/en/stable/development/compiling/compiling_with_mono.html#generate-the-glue


    "you must build a temporary Godot binary with the options tools=yes and mono_glue=no:

    scons p=<platform> tools=yes module_mono_enabled=yes mono_glue=no
    After the build finishes, you need to run the compiled executable with the parameter --generate-mono-glue followed by the 
    path to an output directory. This path must be modules/mono/glue in the Godot directory:

    <godot_binary> --generate-mono-glue modules/mono/glue"


But i dont know what will be generated after that, and what files will be needed to run on XCode, at night we can see this (i'm [GMT-3](https://time.is/pt_br/GMT-3) time)

My Discord ID: Gustavo Maciel / gustavottc#5069

**Comment by brendonion** [comment]
For sure, I'll add you on Discord right now. You are 11 hours ahead of me, so I hope you won't be sleeping when we chat 😬

**Comment by brendonion** [comment]
Oh man nothing is working :(

<img width="529" alt="Screen Shot 2020-11-17 at 11 27 22 AM" src="https://user-images.githubusercontent.com/22459161/99437931-f3463680-28c7-11eb-8185-97521d621d7e.png">

**Comment by gustavottc** [comment]
Closing the issue here due the exporting is working: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/actions/runs/371305010

Currently strill have this error:

```
2020-11-17 08:47:44.142427-0800 godot_app[1049:190092] **ERROR**: Method failed. Returning: __null
2020-11-17 08:47:44.142524-0800 godot_app[1049:190092]    At: modules/mono/csharp_script.cpp:2939:can_instance() - Method failed. Returning: __null
```


But this error is not part of this module, is part of Godot itself, my recommend is create a issue in Godot's Github repository
