### ISSUE TITLE
[BUG] No Signals working

### ISSUE THREAD

**Issue by Vadimledyaev** [Poing-Studios/Godot-AdMob-Android-iOS#26]
Hi, I tried both 3.2.2 and 3.2.3 example projects, they seem to work but only partially - banner and unified_native can be shown.
The problem is I can't find a place where any signal is connected to the plugin singleton. No any signals are emitted from AdMob.tscn.

After adding these lines:
```
_admob_singleton.initialize(is_for_child_directed_treatment, is_personalized, max_ad_content_rating, is_real, get_instance_id())
		_is_initialized = !_is_initialized
_admob_singleton.connect("banner_loaded", self, "_on_admob_singleton_banner_loaded")
```
I got an error:
```
12-07 01:29:37.508 11965 12056 E godot   : **ERROR**: In Object of type 'JNISingleton': Attempt to connect nonexistent signal 'banner_loaded' to method 'Control._on_admob_singleton_banner_loaded'.
12-07 01:29:37.508 11965 12056 E godot   :    At: core/object.cpp:1503:connect() - Condition "!signal_is_valid" is true. Returned: ERR_INVALID_PARAMETER
```

**To Reproduce**
1. open example project
2. add any signal
3. output signal to logcat/debug
4. no signals working

**Expected behavior**
Any signals working

**Smartphone (please complete the following information):**
 - Device: Android cellphone

**Comment by gustavottc** [comment]
Hello, I will check right now, thanks for opening the issue

**Comment by gustavottc** [comment]
Can you tell to me if only this error happens with banner and unified native?

**Comment by gustavottc** [comment]
Should be fixed now: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/actions/runs/404813798


![Screenshot_2020-12-06-23-09-06-629_org.godotengine.godotadmob.jpg](https://user-images.githubusercontent.com/20030153/101301607-1b1a2180-3818-11eb-8636-1f13da0c3a44.jpg)

**Comment by gustavottc** [comment]
Check out this new version: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/actions/runs/404973311

I did a lot of tests and seems working for me

**Comment by Vadimledyaev** [comment]
Hi Gustavo and thanks for a very quick reaction!
I tested it, too - seems to be working perfectly!

Can you please do us a favour and compile the library for Android and iOS? When I'm trying to do that, gradlew returns me an error...

```
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':admob:compileReleaseAidl'.
> java.io.IOException: Синтаксическая ошибка в имени файла, имени папки или метке тома
```

I am sorry, I'm not an expert in Gradle/Java. The last part of error is _"Syntax error in file name, folder name, or volume label"_

Thanks in advance

**Comment by gustavottc** [comment]
Well, this is already compiled: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/releases

Android: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/releases
iOS: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/releases/tag/iOS_v3.0%2B

Check the correct version of your Godot!

**Comment by Vadimledyaev** [comment]
Sorry I was confused with 'iOS' text in zipped file name for Android,
It seems to be working fine now, really appreciate your help!

**Comment by gustavottc** [comment]
Oh, this? "Update export_android_ios_project.yml", this is the commit message, haha

You're welcome, if any issue appear again please let me know.
And if possible give a star for our repository!
