### ISSUE TITLE
[BUG] Game crashing after enabling AdMob

### ISSUE THREAD

**Issue by Luminarcy** [Poing-Studios/Godot-AdMob-Android-iOS#30]
**Describe the bug**
Game crashing after enabling AdMob

**To Reproduce**
1) Use Godot v3.2.4.beta4
2) Run project on device

**Expected behavior**
Game starts with no crashes

**Screenshots**
![image](https://user-images.githubusercontent.com/42573485/103135164-77f65280-46c7-11eb-998c-1e392465b33c.png)

**Smartphone (please complete the following information):**
![image](https://user-images.githubusercontent.com/42573485/103135172-85134180-46c7-11eb-8d04-276a7e4e1a24.png)

**Comment by Luminarcy** [comment]
`12-25 16:20:14.796 18202 18202 E AndroidRuntime: FATAL EXCEPTION: main
12-25 16:20:14.796 18202 18202 E AndroidRuntime: Process: com.luminarcy.echoesofthedeep, PID: 18202
12-25 16:20:14.796 18202 18202 E AndroidRuntime: java.lang.VerifyError: Verifier rejected class com.poing.admob.AdMob: void com.poing.admob.AdMob.<init>(org.godotengine.godot.Godot) failed to verify: void com.poing.admob.AdMob.<init>(org.godotengine.godot.Godot): [0x3] register v1 has type Reference: org.godotengine.godot.Godot but expected Reference: android.app.Activity (declaration of 'com.poing.admob.AdMob' appears in /data/app/com.luminarcy.echoesofthedeep-XcyFjaTbD5upRq0LDa5uZA==/base.apk)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at java.lang.Class.classForName(Native Method)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at java.lang.Class.forName(Class.java:453)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at java.lang.Class.forName(Class.java:378)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at org.godotengine.godot.plugin.GodotPluginRegistry.loadPlugins(GodotPluginRegistry.java:176)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at org.godotengine.godot.plugin.GodotPluginRegistry.<init>(GodotPluginRegistry.java:72)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at org.godotengine.godot.plugin.GodotPluginRegistry.initializePluginRegistry(GodotPluginRegistry.java:104)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at org.godotengine.godot.Godot.onCreateView(Godot.java:583)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:620)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:7157)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6669)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-25 16:20:14.796 18202 18202 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by gustavottc** [comment]
3.2.4 aren't supported yet, what plugin are you trying to use you compiled by yourself or downloaded the precompiled? the 3.2.3 version aren't compatible with 3.2.4

**Comment by Luminarcy** [comment]
I've downloaded precompiled version for 3.2.3. What should i do?

**Comment by gustavottc** [comment]
I will generate an exclusive version for 3.2.4.beta4, but i will not able to say will work because it's in beta version.

Give me some minutes

**Comment by gustavottc** [comment]
Well, iam facing some errors: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/runs/1609647548?check_suite_focus=true

Probably i won't be able to compile by myself, but i will try, be tuned on this issue

**Comment by gustavottc** [comment]
@Luminarcy check it out, i made some changes but i dont know if will work: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/releases/download/Android_v3.2.2%2B/android-template-v3.2.4.zip

**Comment by Luminarcy** [comment]
Thank you, game no longer crashes. Unfortunately, i can't get ads to work.

**Comment by Luminarcy** [comment]
I've double checked id of banner in admob, but i'm getting these errors.

12-26 18:44:15.084  1737  1933 E SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
12-26 18:44:15.189  1737  2003 E SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
12-26 18:44:15.307 17534 17557 E eglCodecCommon: GoldfishAddressSpaceHostMemoryAllocator: ioctl_ping failed for device_type=5, ret=-1
12-26 18:44:16.096 17534 17578 E cr_VariationsUtils: Failed reading seed file "/data/user/0/com.luminarcy.echoes/app_webview/variations_seed": /data/user/0/com.luminarcy.echoes/app_webview/variations_seed (No such file or directory)
12-26 18:44:16.134 17581 17581 E dboxed_process: Not starting debugger since process cannot load the jdwp agent.
12-26 18:44:16.284 17534 17611 E chromium: [ERROR:gl_surface_egl.cc(335)] eglChooseConfig failed with error EGL_SUCCESS
12-26 18:44:16.857 17534 17611 E chromium: [ERROR:gl_surface_egl.cc(335)] eglChooseConfig failed with error EGL_SUCCESS
12-26 18:44:17.082 14078 17669 E Ads     : Cannot determine request type. Is your ad unit id correct?
12-26 18:44:17.111 14078 17503 E Ads     : Cannot determine request type. Is your ad unit id correct?

**Comment by Luminarcy** [comment]
I fixed problem, i forgot to add payment information to admob profile. With test ad everything working perfectly! Thank you.

**Comment by gustavottc** [comment]
> Thank you, game no longer crashes. Unfortunately, i can't get ads to work.
> Also I've got this error. I fixed it by adding tools:replace="android:value" to meta-data. Is this correct?

> tools:replace="android:value" to meta-data

Ty for telling this, it's needed to add this string on <meta-data> when you add the new APPLICATION_ID of your AdMob account because there's an existing APPLICATION_ID of test-ads: i will add this on readme

![Captura de Tela 2020-12-26 às 14 01 57](https://user-images.githubusercontent.com/20030153/103155983-fe239f00-4782-11eb-8f51-0d6f2dedb31b.png)

**Comment by gustavottc** [comment]
> I fixed problem, i forgot to add payment information to admob profile. With test ad everything working perfectly! Thank you.

Nice, if you need the AdMob for iOS on 3.2.4 please let me know, but i recommend you to wait for a stable version for publish your game on Android and iOS.

Thank you for using our module for Godot!

**Comment by Luminarcy** [comment]
> > I fixed problem, i forgot to add payment information to admob profile. With test ad everything working perfectly! Thank you.
> 
> Nice, if you need the AdMob for iOS on 3.2.4 please let me know, but i recommend you to wait for a stable version for publish your game on Android and iOS.
> 
> Thank you for using our module for Godot!

Hello Gustavo, can you please make template for AdMob for iOS on 3.2.4?

**Comment by gustavottc** [comment]
@Luminarcy yes, but it's unstable now, i'm doing the plugin for iOS: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/issues/27

i recommend you to use the 3.2.3 version until this
