### ISSUE TITLE
[FEATURE] Create Wiki for Android and iOS to use the AdMob

### ISSUE THREAD

**Issue by gustavottc** [Poing-Studios/Godot-AdMob-Android-iOS#38]
https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/wiki

**Comment by Xioor** [comment]
Trying to implement this api, could you tell me how can I ask for gdpr prompt again and the idfa prompt? I would like the user to be able to change the setting if they want. Would admob need to be restarted?

**Comment by gustavottc** [comment]
Hello, i think with IDFA you are saying this: 

<img src="https://user-images.githubusercontent.com/20030153/116629658-14f02300-a928-11eb-9499-160673d6aed6.png" width=200>

If yes, then the IDFA will only appear once, I didn't find a way to make it appear more than once for the user to select.

But GDPR, or EU consent using UMP, is possible to appear more than once, but only while you are developing by checking the option `is_test_europe_user_consent = true`, this is not possible for normal users. For users, they will need to reinstall the app.

![Captura de Tela 2021-04-29 às 20 25 40](https://user-images.githubusercontent.com/20030153/116630127-13732a80-a929-11eb-8342-7df83fed32a8.png)


https://developers.google.com/admob/ump/ios/quick-start#reset_consent_state

**Comment by Xioor** [comment]
Hmm for the gdpr consent, I think it for it to by compliant you must be able to easily change the setting while it's in release mode

**Comment by gustavottc** [comment]
I agree, but currently I don't know how to do that, I'm currently very busy working on the [Wiki](https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/wiki).

And soon I intend to do that: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/issues/39 which in my opinion will help a lot in the use of AdMob in Godot

When i finish these things i will surely give a look on change the settings when is release or debug mode, this can be very useful too with test ads.

If you want to try, i think the file you will need to change is this: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/blob/master/ios/plugin/admob/src/main/admob.mm

**Comment by gustavottc** [comment]
Closing the issue since the wiki is "complete"

https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/wiki
