### ISSUE TITLE
[BUG] Error in iOS code when trying to compile godot with module

### ISSUE THREAD

**Issue by sjhennion** [Poing-Studios/Godot-AdMob-Android-iOS#42]
**Describe the bug**
I'm trying to compile godot using Godot-AdMob-Android-iOS as a module, but I'm getting forward declaration errors in the iOS source:

<img width="1271" alt="Screen Shot 2021-01-11 at 10 03 26 PM" src="https://user-images.githubusercontent.com/482282/104264784-4668df80-545a-11eb-875b-643ef777cf17.png">

**To Reproduce**
1. Place `ios/admob` contents into `godot/modules/admob`
2. Place google `*.framework` directories into `godot/modules/admob/lib`
3. Run `scons p=iphone target=debug`

**Expected behavior**
Builds an ios `*.a` file

**Screenshots**

**Smartphone (please complete the following information):**
- Latest Godot-AdMob-Android-iOS as of this writing
- Latest godot from git

**Comment by gustavottc** [comment]
Closed since is duplicated #41
