### ISSUE TITLE
[BUG] framework not found

### ISSUE THREAD

**Issue by martinpelli** [Poing-Studios/Godot-AdMob-Android-iOS#43]
When trying to build with xcode 12.4 with godot 3.2.3 stable xcode show an error : Framework not found GoogleAppMeasurement

I tryied deleting and adding the framework several times and is not working, also adding the framework from general, frameworks, libraries, and embededded content is the same.

 - Device: Iphone 8 plus
 - OS: Mac OS catalina 10.15.6
 - Version 3.2.3 stable

**Comment by martinpelli** [comment]
Solved after search and find that is a problem with Icloud, I disanbled Icloud drive and is working now

**Comment by gustavottc** [comment]
@martinpelli , Nice! You could too do this:

![Captura de Tela 2021-01-06 às 13 40 26](https://user-images.githubusercontent.com/20030153/103795860-45cce500-5025-11eb-87ac-18ef6c6c85c2.png)

![Captura de Tela 2021-01-06 às 13 38 27](https://user-images.githubusercontent.com/20030153/103795850-42395e00-5025-11eb-88e8-c7ff413c7434.png)
