### ISSUE TITLE
[BUG] EGL_BAD_DISPLAY error

### ISSUE THREAD

**Issue by Luminarcy** [Poing-Studios/Godot-AdMob-Android-iOS#48]
**Describe the bug**
With latest admob scene game freezes on startup with 03-23 15:35:42.255 3192-3504/com.luminarcy.echoes E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY) error

**To Reproduce**
1. Enable and configure admob scene.
2. Deploy game to device.
3. See error.

**Expected behavior**
Game should not freeze.

**Screenshots**
![image](https://user-images.githubusercontent.com/42573485/112147418-c1ced600-8bed-11eb-8763-737e1c349df9.png)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 4X
 - OS: Android
 - Version 6.0

**Comment by gustavottc** [comment]
Hey! Thank you for create this issue, i will check it

Do you have other phone to test? Can you test with Android Simulator?

**Comment by gustavottc** [comment]
Can you test this app without AdMob to see if the error still happen?

**Comment by Luminarcy** [comment]
Sorry about delay. Right now i have some problems with singletons.

Somehow this code doesnt print lol
![image](https://user-images.githubusercontent.com/42573485/112160996-c26e6900-8bfb-11eb-80c6-04803c3b5753.png)
![image](https://user-images.githubusercontent.com/42573485/112161036-cbf7d100-8bfb-11eb-849b-2ce0fbc71772.png)

Any ideas why?

**Comment by Luminarcy** [comment]
Also there are Engine.has_singleton("AdMob") in [this line](https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/blob/96a1770230d927989d297cd83b04c8d2419e4422/admob_api/MobileAds.gd#L31) in your code. Is this right?

**Comment by gustavottc** [comment]
The correct is ```Engine.has_singleton("AdMob")```, i don't know where you get the "MobileAds" but its incorrect

**Comment by Luminarcy** [comment]
I carefully reinstalled and reconfigured AdMob module, now everything working perfectly! 😊

**Comment by gustavottc** [comment]
Nice!

What you think about the documentation? There's something needed to be improved?

**Comment by Luminarcy** [comment]
@gustavottc Right now i'm trying to make AdMob for iOS work. After that i may contribute to project's wiki if that okay for you 🙂

**Comment by gustavottc** [comment]
Thank you so much! It will be great if you contribute, but do it only if you feel comfortable

**Comment by Luminarcy** [comment]
> Thank you so much! It will be great if you contribute, but do it only if you feel comfortable

@gustavottc I've added several pages to project's wiki. Also i'd like to make pull request, but i think i don't have rights to make branches.

**Comment by gustavottc** [comment]
@Luminarcy unfortunelly to do that i need to put you the right to "Write" on repository, but this is non-safe because you can also do push to ```master``` branch.

If you want to make pull request, you can create a fork of this repository and then create a pull request of your branch's repository to the ```master``` branch of this repository, what you think?

And thank you a lot for contributing to the wiki!

**Comment by Luminarcy** [comment]
You are welcome 🙂
