### ISSUE TITLE
[BUG] Error compiling Godot for iOS with module for version 3.2.3

### ISSUE THREAD

**Issue by anisc** [Poing-Studios/Godot-AdMob-Android-iOS#52]
**Describe the bug**
Trying to compile for ios but getting this error at 9%:
`anischandoul@aniss-MacBook-Pro godot-3.2.3-stable % scons p=iphone tools=no target=release arch=arm
scons: Reading SConscript files ...
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[  9%] Compiling ==> modules/admob/src/AdMob.mm
clang: warning: optimization flag '-fomit-frame-pointer' is not supported for target 'armv7' [-Wignored-optimization-argument]
In file included from modules/admob/src/AdMob.mm:1:
In file included from modules/admob/src/AdMob.h:7:
modules/admob/src/Interstitial.h:9:36: error: no type or protocol named 'GADInterstitialDelegate' [25]
 @interface Interstitial: NSObject <GADInterstitialDelegate> {
                                    ^
modules/admob/src/Interstitial.h:10:5: error: unknown type name 'GADInterstitial'; did you mean 'GADInterstitialAd'? [2]
     GADInterstitial *interstitial;
     ^~~~~~~~~~~~~~~
     GADInterstitialAd
fix-it:"modules/admob/src/Interstitial.h":{10:5-10:20}:"GADInterstitialAd"
modules/admob/lib/GoogleMobileAds.xcframework/ios-arm64_armv7/GoogleMobileAds.framework/Headers/GADInterstitialAd.h:28:12: note: 'GADInterstitialAd' declared here [2]
 @interface GADInterstitialAd : NSObject <GADFullScreenPresentingAd>
            ^
In file included from modules/admob/src/AdMob.mm:1:
In file included from modules/admob/src/AdMob.h:8:
modules/admob/src/Rewarded.h:10:32: error: no type or protocol named 'GADRewardedAdDelegate' [25]
 @interface Rewarded: NSObject <GADRewardedAdDelegate> {
                                ^
In file included from modules/admob/src/AdMob.mm:6:
In file included from modules/admob/lib/GoogleMobileAds.xcframework/ios-arm64_armv7/GoogleMobileAds.framework/Headers/GoogleMobileAds.h:40:
In file included from modules/admob/lib/GoogleMobileAds.xcframework/ios-arm64_armv7/GoogleMobileAds.framework/Headers/GADCustomNativeAd.h:11:
modules/admob/lib/GoogleMobileAds.xcframework/ios-arm64_armv7/GoogleMobileAds.framework/Headers/GADMediaView.h:27:1: warning: no 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed [-Wobjc-property-no-attribute,2]
 @property(nonatomic, nullable) GADMediaContent *mediaContent;
 ^
modules/admob/lib/GoogleMobileAds.xcframework/ios-arm64_armv7/GoogleMobileAds.framework/Headers/GADMediaView.h:27:1: warning: default property attribute 'assign' not appropriate for object [-Wobjc-property-no-attribute,2]
In file included from modules/admob/src/AdMob.mm:8:
In file included from modules/admob/lib/UserMessagingPlatform.xcframework/ios-arm64_armv7/UserMessagingPlatform.framework/Headers/UserMessagingPlatform.h:1:
In file included from modules/admob/lib/UserMessagingPlatform.xcframework/ios-arm64_armv7/UserMessagingPlatform.framework/Headers/UMPConsentForm.h:1:
In file included from modules/admob/lib/UserMessagingPlatform.xcframework/ios-arm64_armv7/UserMessagingPlatform.framework/Headers/UMPConsentInformation.h:3:
In file included from modules/admob/lib/UserMessagingPlatform.xcframework/ios-arm64_armv7/UserMessagingPlatform.framework/Headers/UMPRequestParameters.h:1:
modules/admob/lib/UserMessagingPlatform.xcframework/ios-arm64_armv7/UserMessagingPlatform.framework/Headers/UMPDebugSettings.h:15:1: warning: no 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed [-Wobjc-property-no-attribute,2]
 @property(nonatomic, nullable) NSArray<NSString *> *testDeviceIdentifiers;
 ^
modules/admob/lib/UserMessagingPlatform.xcframework/ios-arm64_armv7/UserMessagingPlatform.framework/Headers/UMPDebugSettings.h:15:1: warning: default property attribute 'assign' not appropriate for object [-Wobjc-property-no-attribute,2]
modules/admob/src/AdMob.mm:84:60: warning: 'stringWithCString:' is deprecated: first deprecated in iOS 2.0 - Use +stringWithCString:encoding: instead [-Wdeprecated-declarations,32]
         debugSettings.testDeviceIdentifiers = @[ [NSString stringWithCString: getDeviceId()] ];
                                                            ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:525:1: note: 'stringWithCString:' has been explicitly marked deprecated here [2]
 + (nullable id)stringWithCString:(const char *)bytes API_DEPRECATED("Use +stringWithCString:encoding: instead", macos(10.0,10.4), ios(2.0,2.0), watchos(2.0,2.0), tvos(9.0,9.0));
 ^
modules/admob/src/AdMob.mm:124:104: warning: 'stringWithCString:' is deprecated: first deprecated in iOS 2.0 - Use +stringWithCString:encoding: instead [-Wdeprecated-declarations,32]
                 GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @ [ [NSString stringWithCString: getDeviceId()] ];
                                                                                                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:525:1: note: 'stringWithCString:' has been explicitly marked deprecated here [2]
 + (nullable id)stringWithCString:(const char *)bytes API_DEPRECATED("Use +stringWithCString:encoding: instead", macos(10.0,10.4), ios(2.0,2.0), watchos(2.0,2.0), tvos(9.0,9.0));
 ^
modules/admob/src/AdMob.mm:125:87: warning: 'stringWithCString:' is deprecated: first deprecated in iOS 2.0 - Use +stringWithCString:encoding: instead [-Wdeprecated-declarations,32]
                 NSLog(@"on Testing Real Device: testDeviceIdentifiers: %@", [NSString stringWithCString: getDeviceId()]);
                                                                                       ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSString.h:525:1: note: 'stringWithCString:' has been explicitly marked deprecated here [2]
 + (nullable id)stringWithCString:(const char *)bytes API_DEPRECATED("Use +stringWithCString:encoding: instead", macos(10.0,10.4), ios(2.0,2.0), watchos(2.0,2.0), tvos(9.0,9.0));
 ^
modules/admob/src/AdMob.mm:158:56:{158:56-158:75}{158:34-158:41}: warning: enum values with underlying type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead [-Wformat,33]
                     NSLog(@"%s : %ld", "GADMobileAds", adapterStatus.state);
                                  ~~~                   ^~~~~~~~~~~~~~~~~~~
                                  %ld                   (long)
fix-it:"modules/admob/src/AdMob.mm":{158:34-158:37}:"%ld"
fix-it:"modules/admob/src/AdMob.mm":{158:56-158:56}:"(long)"
modules/admob/src/AdMob.mm:172:52:{172:52-172:71}{172:30-172:37}: warning: enum values with underlying type 'NSInteger' should not be used as format arguments; add an explicit cast to 'long' instead [-Wformat,33]
                 NSLog(@"%s : %ld", "GADMobileAds", adapterStatus.state);
                              ~~~                   ^~~~~~~~~~~~~~~~~~~
                              %ld                   (long)
fix-it:"modules/admob/src/AdMob.mm":{172:30-172:33}:"%ld"
fix-it:"modules/admob/src/AdMob.mm":{172:52-172:52}:"(long)"
9 warnings and 3 errors generated.
scons: *** [modules/admob/src/AdMob.iphone.opt.arm.o] Error 1
scons: building terminated because of errors.
anischandoul@aniss-MacBook-Pro godot-3.2.3-stable % `

before this error there was another error about on interstitial.h:
#import <GoogleMobileAds/GADInterstitial.h> I changed it to #import <GoogleMobileAds/GADInterstitialAd.h>

**To Reproduce**
terminal and scons p=iphone tools=no target=release arch=arm
tried with master and 3.0_3.2.3 branch 
and GoogleMobileAdsSdkiOS-8.3.0 and 7.69.0


**Smartphone (please complete the following information):**
 - OS: Big Sur 11.2.3

**Comment by gustavottc** [comment]
Hi, thank you for create the issue, please try with this version of GoogleMobileAdsSDK: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/releases/download/iOS_v3.0%2B/googlemobileadssdkios.zip

**Comment by gustavottc** [comment]
- The correct for the ```master``` branch is ```#import <GoogleMobileAds/GADInterstitial.h> ``` because is built with version 7.69
- You need to put the ```.framework``` inside this [.zip](https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/releases/download/iOS_v3.0%2B/googlemobileadssdkios.zip) into this folder: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/tree/master/ios/admob/lib

**Comment by gustavottc** [comment]
@anisc i'm waiting for Godot 3.4 versions release to update the ```master``` branch, until this you need to do these things i said above this message

**Comment by anisc** [comment]
I'm going to delete everything and start from a clean slate, will get back to you tomorrow but I did try both library tho. thank you for getting back to me

**Comment by gustavottc** [comment]
@anisc Ok, if this didn't solve please tell me

**Comment by anisc** [comment]
@gustavottc successfully built using the googlemobileadssdkios.zip you sent. thank you for your help
but it seems that only test ads work. I will try to make it work but that's a different issue.

**Comment by gustavottc** [comment]
Awesome! 

The real ads only appear if you add the app on AdMob, here: https://support.google.com/admob/answer/9989980?hl=en

**Comment by anisc** [comment]
I was using  Shin-NiL plugin, it works great on android, but because I want to publish the app on ios too I switch to this one.

**Comment by gustavottc** [comment]
Only iOS have this issue, Android will work fine without add the app on AdMob website.

To fix this you need to publish your game to App Store and wait to appear to add, it can take some days.

I strong recommend you to use only one Plugin, using two plugin to the same thing it's not recommended.

**Comment by anisc** [comment]
@gustavottc Bro wanted to give you an update.
Waited waited waited sent emails to admob ... but nothing happened until today I found this website: 
[Google Mobile Ads SDK Developers](https://groups.google.com/g/google-admob-ads-sdk/c/_S4SfJykLJI)
gave them the apple id and now I can see the ads and was able to link my app.
