### ISSUE TITLE
[BUG] [IOS]adView:didFailToReceiveAdWithError: Request Error: No ad to show.

### ISSUE THREAD

**Issue by anisc** [Poing-Studios/Godot-AdMob-Android-iOS#53]
On android it works great with this plugin
This issue is only on IOS 
When I use the test app id and unit id I get the test ad showing but when I change the ids to mine nothing shows and I have this error:
<Google> Invalid Request. Cannot determine request type. Is your ad unit id correct?
adView:didFailToReceiveAdWithError: Request Error: No ad to show.
interstitial:didFailToReceiveAdWithError: Request Error: No ad to show.
I'm using those same ids with Shin-NiL plugin and the ads are showing. so I'm pretty sure I did something work while implementing the plugin 
An other question: How can I print the error code number ?

**Comment by gustavottc** [comment]
Only iOS have this issue, Android will work fine without add the app on AdMob website.

To fix this you need to publish your game to App Store and wait to appear to add, it can take some days.

I strong recommend you to use only one Plugin, using two plugin to the same thing it's not recommended.

I will close this issue since it's a issue of AdMob and not of this Plugin

https://support.google.com/admob/answer/9469204?hl=en

![Captura de Tela 2021-04-06 às 16 41 33](https://user-images.githubusercontent.com/20030153/113769086-f5822380-96f6-11eb-8998-5d8ebc3f7932.png)

**Comment by gustavottc** [comment]
The real ads only appear if you add the app on AdMob, here: https://support.google.com/admob/answer/9989980?hl=en

- How can I print the error code number ?

On this [file](https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/blob/master/example/admob_api/MobileAdsBase.gd) you will have some functions called "banner_failed_to_load", "interstitial_failed_to_load", "rewarded_ad_failed_to_show", "unified_native_failed_to_load", like: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/blob/master/example/admob_api/MobileAdsBase.gd#L67

You can do a: ```print(error_code)``` and check here what the ```error_code``` means: 

Android: https://developers.google.com/android/reference/com/google/android/gms/ads/AdRequest
iOS: https://developers.google.com/admob/ios/api/reference/Enums/GADErrorCode

**Comment by gustavottc** [comment]
One last thing: If you publish you game to App Store and it takes more than 7 days to appear to add to AdMob, you can create a thread here, maybe the Google people will streamline the process of listing your app to add:

https://support.google.com/admob/thread/new?hl=en

It happened to me, I added an app and I waited for approximately 2 weeks to appear and even then it didn't appear, so I created a thread, after a day it appeared to add and the ads started to appear

**Comment by anisc** [comment]
> I strong recommend you to use only one Plugin, using two plugin to the same thing it's not recommended.
What do you mean ? 
    Error Code 1 : ERROR_CODE_INVALID_REQUEST

    The ad request was invalid; for instance, the ad unit ID was incorrect.

    This commonly suggests that the Ad Request implementation is not as per the SDK’s requirements - Resources like the  sample codes and sample apps provided in the developer documentation can help in implementing the functions correctly. 
    so this is an implementation issue.
    What was the code you were getting ?

**Comment by gustavottc** [comment]
@anisc If you use two plugins to the same thing maybe it causes a conflict and your game will not know which is the correct plugin, besides having duplicate code so I recommend you only use the Shin-Nil or Poing Plugin.

Sorry i don't remember the code but i think was: [```GADErrorInvalidRequest```](https://developers.google.com/admob/ios/api/reference/Enums/GADErrorCode#/c:@E@GADErrorCode@GADErrorInvalidRequest)

Please try with [test-ids](https://developers.google.com/admob/ios/test-ads#demo_ad_units):

Banner: ```ca-app-pub-3940256099942544/2934735716```
Interstitial: ```ca-app-pub-3940256099942544/4411468910```
Rewarded: ```ca-app-pub-3940256099942544/1712485313```


If the test-ids works then the reason why is not appearing the real ads is this: https://support.google.com/admob/answer/9469204?hl=en

![image](https://user-images.githubusercontent.com/20030153/113797015-d13e3b00-9726-11eb-8281-00a4ab7f475e.png)

**Comment by anisc** [comment]
I took off Shin-Nil plugin I'm only using this one but I was saying that when I used Shin-Nil plugin with those same ids it worked.
any way thank you so much for your help will try it and get back to you.

**Comment by gustavottc** [comment]
@anisc You're welcome! And know that if the test ad worked then there is nothing wrong with the Plugin, probably your iOS app is new and you need to publish to the App Store and link to AdMob, after that your ads will work normally.

**Comment by anisc** [comment]
@gustavottc test ids work, I will wait then :) 
when I use test id and change is_real, would there be any change ?

**Comment by gustavottc** [comment]
@anisc I guess no, only on real ads.

On real ads this happens: https://developers.google.com/admob/ios/test-ads#enable_test_devices

```
If you want to do more rigorous testing with production-looking ads, you can now configure your device as a test device and use your own ad unit IDs that you've created in the AdMob UI. Test devices can either be added in the AdMob UI or programmatically using the Google Mobile Ads SDK.
```

**Comment by gustavottc** [comment]
https://support.google.com/admob/thread/95147767?hl=en

**Comment by anisc** [comment]
yeah still nothing, no ads it have been 5 days since it was on the app store, still waiting. 
Thank you again bro for the follow up :)

**Comment by gustavottc** [comment]
Try to rate your game, maybe will make it appear faster.

When your game appear here, then i'm sure your ads will work.

![Captura de Tela 2021-04-12 às 20 51 45](https://user-images.githubusercontent.com/20030153/114476641-fc1a0a80-9bd0-11eb-8be2-d217030cc69c.png)

![Captura de Tela 2021-04-12 às 20 51 15](https://user-images.githubusercontent.com/20030153/114476579-d7be2e00-9bd0-11eb-9b54-e5c05b5ec890.png)

**Comment by anisc** [comment]
@gustavottc Hi Bro wanted to give you an update.
so I have been waiting for 3 week now, sent emails to admob but nothing can't link my app nor see real ads, until I found this website today:
[Google Mobile Ads SDK Developers](https://groups.google.com/g/google-admob-ads-sdk/c/_S4SfJykLJI)
opened a discussion and gave them the Apple App Store connect app id, by the end of the day every thing was fixed, was able to connect the app and real ads started show now.

**Comment by gustavottc** [comment]
Hey @anisc good to hear, i never saw this website.

The Godot 3.3 version has arrived and we finished the AdMob iOS Plugin, if you want to test you are welcome: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS#ios-v33

More detailed documentation: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/wiki/iOS-Plugin

**Comment by anisc** [comment]
@gustavottc sure I tested the android version work like a charm, and I will be testing the ios one soon will let you know how it goes.
Thank you so much tho for all your hard work bro !!
