### ISSUE TITLE
[BUG] Does this work with 3.3 stable ? 

### ISSUE THREAD

**Issue by anisc** [Poing-Studios/Godot-AdMob-Android-iOS#54]
**Describe the bug**
On my project I have firebase and facebook (DrMoriarty), it build and run but every time I add this plugin I get this error :
 com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
     The number of method references in a .dex file cannot exceed 64K.

**Smartphone (please complete the following information):**
I'm building on an android S9 using macos

**Comment by gustavottc** [comment]
Thanks for opening the issue, I finished the Github Actions yesterday but i have not test yet because I was too tired, I will do this soon and give a feedback for you.

**Comment by gustavottc** [comment]
![Screenshot_2021-04-23-13-34-35-620_org.godotengine.godotadmob.jpg](https://user-images.githubusercontent.com/20030153/115902308-b236ed00-a438-11eb-9053-65f10d7abbfa.jpg)

I tested here and it's working fine on Android

**Comment by gustavottc** [comment]
Can you test with the example project located here? 

https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/tree/master/example

**Comment by anisc** [comment]
thank you bro :) 
the issue was with the godot gradle config the minsdk was 16 had to change it to 21 to enable multidex

**Comment by gustavottc** [comment]
@anisc Awesome! This is my `config.gradle` just in case if you want to compare (Was automatic generated by Godot):

![Captura de Tela 2021-04-23 às 14 07 47](https://user-images.githubusercontent.com/20030153/115905976-4905a880-a43d-11eb-8e7d-fcbfad2486a8.png)

**Comment by anisc** [comment]
Did you use this plugin with an other one because to use multidex minSdk have to be higher than 20 or you will have to use "multiDexEnabled true" with the default config 
https://developer.android.com/studio/build/multidex

**Comment by gustavottc** [comment]
No, i have not tried yet, i only use with this plugin.

If the issue still persists i recommend you open an issue on Godot's Github project: https://github.com/godotengine/godot. I think theres nothing i can do with the plugin.

**Comment by anisc** [comment]
@gustavottc no worries bro the issue is already fix (ticket is closed) I Was just curious, if you used it with other plugin without the multidex enabled.
