### ISSUE TITLE
[BUG] Rewarded Ads do not work on Android but Interstitial Ads do

### ISSUE THREAD

**Issue by Tekuzo** [Poing-Studios/Godot-AdMob-Android-iOS#67]
**Describe the bug**
Running from Godot 3.3
Calling show_rewarded() does not display an ad
when I call load_rewarded() the rewarded_loaded variable never changes to true.

I connected the rewarded_ad_failed_to_load signal and have a print() command in the function and that signal never fires.

Interstitial ads load just fine.

I am using the android-standard-template-v3.3.zip for my project.

**To Reproduce**
1. Unzip android-standard-template-v3.3.zip and put files into res:// of my project
2. Install plugin to res://android/plugins
3. Add Project ID to AndroidManifest.xml
4. Add MobileAds as a singleton
5. Call MobileAds.load_rewarded() when player character dies
6. Call MobileAds.show_rewarded() when player pushes the rewarded ad button

**Expected behavior**
I expect a rewarded ad to work, like it works on iOS when I press the button.

**Screenshots**
![Screenshot_20210507-132820](https://user-images.githubusercontent.com/6944363/117487097-a1a66c80-af38-11eb-9311-6889d8b4eac0.png)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3
 - OS: Android 11
 - Version 

**Additional context**
I have disabled all other plugins while I try to debug this issue.

**Comment by gustavottc** [comment]
Thank you for using our Plugin! Are you testing with the example project? I think this is strange to not work because on my app is working normally.

Please try with example project to see how it works

**Comment by gustavottc** [comment]
Oh, I saw you are testing with example project, but the IDs of Ads are the testing IDs?

**Comment by gustavottc** [comment]
I will investigate this, probably the ID of rewarded is wrong on example project

**Comment by Tekuzo** [comment]
Yes I am using your example project. I left the IDs alone and I am using the IDs that were included.

**Comment by gustavottc** [comment]
I'm checking this right now, thanks for report it

**Comment by gustavottc** [comment]
@Tekuzo , i tested with my IDs of my apps released and it's working, but with the test ID it's not.

I think Google disabled this ID of rewarded test: `ca-app-pub-3940256099942544/5224354917`

Check this conversation here posted yesterday: https://groups.google.com/g/google-admob-ads-sdk/c/VWlagjvdxm4

**Comment by gustavottc** [comment]
I noticed the `admob_api` is not receiving the `error_code : int` as parameter, so will not emit the signal, fixing on next update.

**Comment by Tekuzo** [comment]
Ok, so then the Plugin Will probably still work with the live id from my ad in admob and its that they disabled the test id?

Is there an ID I can put into the test app to make sure that this works before I publish?

**Comment by gustavottc** [comment]
@Tekuzo i just send the update to the repository, please download again the Plugin and update the `admob_api`.

> Is there an ID I can put into the test app to make sure that this works before I publish?
Unfortunelly the IDs that i have are for apps on production, i can't send to you 😢 

But try to create your own ones on https://admob.google.com/ and make sure to mark `Is Real` to `false`

**Comment by gustavottc** [comment]
@Tekuzo 

A random question, what name do you think would be best to be able to call the admob_api (singleton) methods?

1. AdMob (I think this is the best, but it is not possible to use it due to a bug with Plugins, it would only work if I change the Android and iOS Plugin name)
2. MobileAds (it's the current name, comes from AdMob: https://developers.google.com/admob/android/quick-start#initialize_the_mobile_ads_sdk)
3. GoogleAdMob
4. AdMobAPI
5. Any other that you prefer and is not listed


I think the name MobileAds may not be very good, so I’m asking this question to see if it’s better to switch to some other name

**Comment by Tekuzo** [comment]
MobileAds is fine. AdMob might imply some sort of affiliation?

**Comment by Tekuzo** [comment]
Where do I set Is Real to Fale?
Inside of the Admob website or inside of the plugin?

**Comment by gustavottc** [comment]
@Tekuzo , you van change inside `MobileAds.tscn` or `MobileAds.gd`

**Comment by Tekuzo** [comment]
Thank you very much. I got it working.
