### ISSUE TITLE
[BUG] Godot 3.3 export in android

### ISSUE THREAD

**Issue by ATOshailesh** [Poing-Studios/Godot-AdMob-Android-iOS#73]
Hi,
**Describe the bug**
_admob_singleton is found but get signal initialization_complete status **NOT_READY** [0].
so, not load_interstitial my ad  👎🏻 

**To Reproduce**
https://github.com/Poing-Studios/Godot-AdMob-Android-iOS#android-v322

also same issues in example 
:: https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/tree/master/example

how can i figure out!!

**Comment by ATOshailesh** [comment]
Also i check in ios,
It's same issues in ios 14 [not show test ad] but ios 12 working fine [show test ad].

**Comment by gumaciel** [comment]
Thanks for open this issue, i will check it out soon.

![image](https://user-images.githubusercontent.com/20030153/119361376-f872ac80-bc81-11eb-8a06-01f184f7f973.png)

Have you did this?

**Comment by gumaciel** [comment]
What's the Godot Version you are trying to use this Plugin? 3.3 or 3.3.1?

**Comment by ATOshailesh** [comment]
Yes **use custom build** check mark and also **plugin admob** check mark.
Godot version 3.3 and **android-standard-template-v3.3** both are same.

**Comment by gumaciel** [comment]
Hey, sorry for delay, what phone and Android Version you are trying to use the Plugin?

**Comment by ATOshailesh** [comment]
Phone: OPPO F3, android version : 6.0

**Comment by gumaciel** [comment]
@ATOshailesh , Maybe the Android Versions is the cause of problem, we are using the newest Google Mobile Ads SDK: 20.1.0, i don't know if they stop to work on this version, do you have other phone to test? 

Can you please test with an Android Simulator as well? I'm testing on Android 10 and it's working normally, sorry for delay i'm very busy these days.

**Comment by ATOshailesh** [comment]
Also i am try to other android tablet but not success.
_on_AdMob_initialization_complete status get not_ready.

using : https://github.com/Shin-NiL/Godot-Android-Admob-Plugin
it's work in android device but not in ios :<

**Comment by gumaciel** [comment]
@ATOshailesh , i made a .APK with 3.3 version to you test, on my Android 10 is working normally.

https://www.mediafire.com/file/9le5357o24uwzb8/AdMob33standard.apk/file

**Comment by gumaciel** [comment]
@ATOshailesh please see this video tutorial that i made (maybe is not good because is the very first video tutorial i made 🤣 )

https://www.youtube.com/watch?v=5J_RP2sCf7Y

**Comment by gumaciel** [comment]
Hey @ATOshailesh , any news?

**Comment by ATOshailesh** [comment]
sorry for delay, 
Nice one to creating a video,
i follow same as in video but get status 0 in **initialization_complete** 
mark : new upload android-standard-template-v3.3.zip -- you forgot **AdMob.gdap** file so, i used before download file like inside dependencies Google Mobile Ads SDK: 20.1.0

**Comment by gumaciel** [comment]
Hey @ATOshailesh do you have Discord? Please join here for a fast conversation: https://discord.gg/FAMNVzBJ

I saw here the .gdap is missing, I will fix that, thank you for telling me.

**Comment by gumaciel** [comment]
@ATOshailesh please test it now

**Comment by ATOshailesh** [comment]
Sorry I haven't Discord.
i test too many time but not getting to ready status in initialization_complete.

**Comment by gumaciel** [comment]
Hi @ATOshailesh  have you tested this .APK?

https://www.mediafire.com/file/9le5357o24uwzb8/AdMob33standard.apk/file

**Comment by ShaileshDhaduk** [comment]
Hey @gumaciel , this apk test it's fantastic working in my android device.

**Comment by ATOshailesh** [comment]
Hey @gumaciel , this apk test it's fantastic working in my android device.

**Comment by gumaciel** [comment]
Well, if this APK is working, then theres nothing wrong with the Plugin, i guess.

I think you are doing something wrong, or your computer is not properly configured to export with Android Plugins.

Please try to join in our Discord, then i can share with you my screen, so you will be able to make the Plugin works for you as well.

https://discord.gg/FAMNVzBJ

**Comment by ShaileshDhaduk** [comment]
Hi @gumaciel Very thankful you support me.
Finally i create my won plugin because this one also fail in ios 14.
https://github.com/ShaileshDhaduk/Godot-Admob-android-ios

**Comment by gumaciel** [comment]
Hi @ShaileshDhaduk , congratulations, but as you can see on this video it works on iOS 14: https://m.youtube.com/watch?v=pkTUVArtG7Y&t=980

**Comment by ShaileshDhaduk** [comment]
wow @gumaciel  it's working in ios 14.
remove old plugins/bin/ file and again download to add.
Thank you so much.

**Comment by gumaciel** [comment]
Hi @ATOshailesh any update?
