### ISSUE TITLE
[BUG]Error compiling

### ISSUE THREAD

**Issue by bubutime** [Poing-Studios/Godot-AdMob-Android-iOS#74]
**Describe the bug**
Error compiling.
godot 3.3.2

**Additional context**
![Untitled](https://user-images.githubusercontent.com/68721236/120144625-d4304600-c214-11eb-83bd-5c3ce3e3222c.png)

**Comment by gumaciel** [comment]
@bubutime Hey! Please try to do with this video tutorial: https://www.youtube.com/watch?v=5J_RP2sCf7Y

**Comment by bubutime** [comment]
im actually using the example project, i just change the necessary files to 3.3.2 from your download page.  install android bundle, etc. and yeah that shows the error.

anyway, ill try from scratch

**Comment by gumaciel** [comment]
Hey @bubutime any news?

**Comment by bubutime** [comment]
> Hey @bubutime any news?

eyy, so i checked it using a different computer and using my main project. so what i did was, remove other plugins first then reinstall android bundles then compile and it works.

**Comment by gumaciel** [comment]
Great news, thank you for using our Plugin!

**Comment by bubutime** [comment]
> Great news, thank you for using our Plugin!

yeah, but apparently its still not working on another computer. idk, either android sdk or java issue

**Comment by gumaciel** [comment]
I guess it is, I export the game in three different computers that I have and is normally. :(
