### ISSUE TITLE
[FEATURE] Remove Native Ad from Plugin

### ISSUE THREAD

**Issue by gumaciel** [Poing-Studios/Godot-AdMob-Android-iOS#75]
**Is your feature request related to a problem? Please describe.**
Native Ads won't work well with a game camera movement.

**Describe the solution you'd like**
Remove and only use the Banner, Interstitial and Rewarded, if the company wants to implements Native Ads, the company needs to do that without AdMob.

**Describe alternatives you've considered**
Implement by yourself a Native Ad without AdMob.

**Additional context**
https://gameanalytics.com/blog/native-ads-in-mobile-games/
https://medium.com/@greedy_game/ad-tech-simplified-what-are-in-game-native-ads-cb19c3563081

Ps: This can be dropped in the future, so let's just comment on code parts we've already done of ad native.

**Comment by djrain** [comment]
Hi, is there any chance to add native ads back to the plugin at some point? Would be very nice to have as they are much more effective than banners. Of course I understand if you don't have time for it, if it's possible I may be interested to help with this.

**Comment by gumaciel** [comment]
Unfortunately I don't have time as you mentioned, I have other things planned to do and I believe that this new feature is not that necessary for most games, besides being very complicated because it deals with native elements of the screen of the user, one thing that I think would be extremely difficult or even impossible would be to add native ads in 3D games as in the links above, I believe that neither Unreal nor Unity has this type of behavior.

But if more people ask to come back with the Native ad type I can go back to making improvements to the Native ad.

I really appreciate that you said that you are interested in helping if possible join our Discord: https://discord.gg/YEPvYjSSMk and then we can work together, I really need to improve the documentation and refactor the Plugin architecture to make it easy to understand for new users.

I will leave this Issue closed for now, but if in the future we develop Native Ads again, we will reopen it.
