### ISSUE TITLE
[FEATURE] How to get Banner width and height

### ISSUE THREAD

**Issue by kyoz** [Poing-Studios/Godot-AdMob-Android-iOS#78]
**Is your feature request related to a problem? Please describe.**
Is there a way which i can get the banner width and size after it's displayed.

In old Admob Plugin i'v used. It's have api like getBannerWidth(), getBannerHeight()...Which is very helpful for adding gap to the GUI and ensure all content not display under Banner Ad.

**Describe the solution you'd like**
There should be getBannerWidth(), getBannerHeight() api

**Comment by gumaciel** [comment]
@kyoz thank you for suggesting this, I will definitely do this on future versions, stay tuned! ❤️

**Comment by gumaciel** [comment]
@kyoz  I have just commited the changes, please try it out.

Ps: Should work on Android and iOS

**Comment by gumaciel** [comment]
Methods name:

get_banner_width, 
get_banner_height, 
get_banner_width_in_pixels, get_banner_height_in_pixels

**Comment by kyoz** [comment]
Hi @gumaciel, i'v tested and it work well on Android

**Comment by gumaciel** [comment]
Thank you, I will close this issue since I also tested on Android and iOS and both are working, if some bug appear, please let us know.
