### ISSUE TITLE
[BUG] Close ios app to crash

### ISSUE THREAD

**Issue by ShaileshDhaduk** [Poing-Studios/Godot-AdMob-Android-iOS#79]
**Describe the bug**
Add admob plugin after close app to crash app.

**To Reproduce**
1. Admob plugin add
2. Run in iphone 8 or iphone 6 device
3. show one time interstitial ads.
4. home button press to close app then app crash

**Expected behavior**
Any time app close to free admob instance.

**Screenshots**
![Screenshot 2021-06-15 at 6 18 56 PM](https://user-images.githubusercontent.com/31446601/122169959-a9442400-ce9b-11eb-9c3a-f0a42b864dd9.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone8]
 - OS: [e.g. iOS14]
 - Version [e.g. 3.3]

**Comment by gumaciel** [comment]
@ShaileshDhaduk thanks for reporting it, i will check it out.

**Comment by gumaciel** [comment]
https://user-images.githubusercontent.com/20030153/122331432-31154700-cf0b-11eb-83f6-8b362e55c785.mov

@ShaileshDhaduk tested here on iPhone 8, iOS 14 and everything is ok, but i could not test on iPhone 6 because iOS 14 is not available for iPhone 6.

**Comment by ShaileshDhaduk** [comment]
Hey @gumaciel  home press after close app to detect crash.

**Comment by gumaciel** [comment]
@ShaileshDhaduk Sorry but i don't manage to get the error, these was the last logs of one of my tries:

```
start animation!
2021-06-17 23:22:40.639079-0300 AdMobAddon[1883:82817] [aurioc] AURemoteIO.h:323:entry: Unable to join I/O thread to workgroup ((null)): 2
******** stop animation!
iphone_finish
2021-06-17 23:22:45.876920-0300 AdMobAddon[1883:81305] deinit admob plugin
2021-06-17 23:22:45.877094-0300 AdMobAddon[1883:81305] deinitialize admob
```

![Captura de Tela 2021-06-17 às 23 24 14](https://user-images.githubusercontent.com/20030153/122497038-21f1d000-cfc3-11eb-9fe3-17e860ed42c3.png)


I tried a lot of times and don't get the error.

If possible please join on our Discord and you can try to show to me: https://discord.gg/FAMNVzBJ

**Comment by gumaciel** [comment]
Also please check if the errors also happens without the Plugin, is yes, then the problem is out of scope of thisnl repository and you need to report to Godot. 

But if the error only happens with the Plugin, then we need to fix that

**Comment by ShaileshDhaduk** [comment]
@gumaciel Also i can't understand remove plugin after reinstall admob plugin to error gone. :<

**Comment by gumaciel** [comment]
Hi @ShaileshDhaduk , i think you manage to work the plugin, but if not, you can Reopen this Issue or join on our discord: https://discord.gg/FAMNVzBJ
