### ISSUE TITLE
[BUG]Rewarded Ads not Loading on iOS

### ISSUE THREAD

**Issue by Tekuzo** [Poing-Studios/Godot-AdMob-Android-iOS#82]
**Describe the bug**
Test ads not displaying when user selects "Ask App Not To Track" on iOS 14 devices.

**To Reproduce**
When promoted to allow for tracking, if the user selects the do not track button then rewarded ads do not load.

**Expected behavior**
The ad does not buffer and the _on_MobileAds_rewarded_ad_failed_to_load signal does not get emitted
![IMG_0184](https://user-images.githubusercontent.com/6944363/122766200-41ad2080-d26f-11eb-921c-99cfd13c5e00.PNG)

**Screenshots**
Console Output

`2021-06-21 08:29:09.989764-0400 Captain Skyrunner[372:9702] Calling load_rewarded`

`2021-06-21 08:29:09.989932-0400 Captain Skyrunner[372:9702] rewarded will load with the id`

`2021-06-21 08:29:09.989984-0400 Captain Skyrunner[372:9702] [My Admob App ID was output here]`

`2021-06-21 08:29:09.994954-0400 Captain Skyrunner[372:9702] <Google> To get test ads on this device, set: GADMobileAds.sharedInstance.requestConfiguration.testDeviceIdentifiers = @[ @"e484e6d6f7ca8ecd79bb89626c9b8dff" ];`

`2021-06-21 08:29:09.995798-0400 Captain Skyrunner[372:9702] <Google> Note that test device identifiers may be reset when uninstalling and reinstalling the application.`

`2021-06-21 08:29:10.052532-0400 Captain Skyrunner[372:10127] [connection] nw_endpoint_handler_set_adaptive_read_handler [C3.1.1 172.217.1.14:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for read_timeout failed`

`2021-06-21 08:29:10.052604-0400 Captain Skyrunner[372:10127] [connection] nw_endpoint_handler_set_adaptive_write_handler [C3.1.1 172.217.1.14:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for write_timeout failed`

`2021-06-21 08:29:10.156482-0400 Captain Skyrunner[372:9906] [connection] nw_endpoint_handler_set_adaptive_read_handler [C4.1.1 172.217.164.194:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for read_timeout failed`

`2021-06-21 08:29:10.156530-0400 Captain Skyrunner[372:9906] [connection] nw_endpoint_handler_set_adaptive_write_handler [C4.1.1 172.217.164.194:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for write_timeout failed`

`2021-06-21 08:29:10.368262-0400 Captain Skyrunner[372:9702] Rewarded ad failed to load with error: Request Error: No ad to show.`

`2021-06-21 08:29:10.368406-0400 Captain Skyrunner[372:9702] error while creating reward`

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2nd generation
 - OS: iOS 14.6

**Additional context**

**Comment by gumaciel** [comment]
Hi @Tekuzo thank you for using our Plugin!

I'm seeing you are using on your project, can you please test it out with the example project located on the Editor Plugin?

**Comment by Tekuzo** [comment]
You mean using the new version of the plugin?

**Comment by gumaciel** [comment]
@Tekuzo yes, soon i will drop a new version 0.2.1 and you can try with this one

**Comment by gumaciel** [comment]
Hi @Tekuzo i released a new version, please try it out: https://github.com/Poing-Studios/Godot-AdMob-Editor-Plugin/releases/tag/0.2.2

**Comment by Tekuzo** [comment]
Thanks. The ads are now playing on iOS when the user selects not to be tracked.

I noticed that it introduced an audio bug that did not exist before.

When I try to authenticate to gamecenter, using the official plugin, the music on my game cuts a little bit, and it didn't used to before. I am not sure if something is happening with both singletons being active.

I have mitigated the audio issue by having my music play the music in a dedicated thread, and logging into Game Center and iCloud is also in its own dedicated thread.

Thank you very much.

**Comment by Tekuzo** [comment]
Actually, that screen from the very first screenshot, "Captain Skyrunner wants to stay free for you"

that screen no longer displays with the updated plugin.

**Comment by gumaciel** [comment]
Hi @Tekuzo , Google says this: https://developers.google.com/admob/ump/ios/quick-start#app_tracking_transparency

`While testing, remember that per Apple's requirements, the IDFA ATT dialog will only appear a single time since requestTrackingAuthorization: is a one-time request. To make the alert appear a second time, you must uninstall and reinstall your app on your test device.`

**Comment by Tekuzo** [comment]
Yes, I uninstall and re-install the app every time I test

**Comment by gumaciel** [comment]
Please do not export your Game to App Store or Google Play with the Plugin until I release a new video tutorial today, I made some changes and I will need to redo the video.

**Comment by gumaciel** [comment]
> Yes, I uninstall and re-install the app every time I test

And is still not appearing? Tonight I will give a look about it

**Comment by Tekuzo** [comment]
Yes, it is still not appearing.

**Comment by gumaciel** [comment]
![Captura de Tela 2021-06-24 às 22 43 11](https://user-images.githubusercontent.com/20030153/123356178-908fda00-d53d-11eb-84b7-d57465520c6e.png)

@Tekuzo , the dialog that you were saying was this one?

**Comment by Tekuzo** [comment]
It was displaying in an older version of your plugin.

I am not sure which one it was. I believe I downloaded it the day that 3.3 stable was released. I was using the older version of your plugin until yesterday when I updated to 0.1.3

**Comment by gumaciel** [comment]
@Tekuzo we submitted an update to Godot in 1 week ago and they still don't approve: https://godotengine.org/asset-library/asset/edit?filter=AdMob 

The current version is 0.2.2, which you can download here: https://github.com/Poing-Studios/Godot-AdMob-Editor-Plugin/tags

In a few days (i guess 2 days) we will create a 0.3.0 version which will have much more improvements and features, if possible please wait.

**Comment by Tekuzo** [comment]
Sure, I will wait for your new version.

**Comment by gumaciel** [comment]
@Tekuzo 0.3.0 is released, please watch this video: https://youtu.be/mmZZj0kC7Jk

It's for Android, but you will still need to do the same for iOS here: 
![Captura de Tela 2021-06-26 às 00 39 04](https://user-images.githubusercontent.com/20030153/123500788-ebe1cb00-d616-11eb-9d2b-9cbfc9ac9495.png)

I can't create a good video right now, there's just me working on this plugin, and it's a lot of work :( but in a few days a well explained video will come out

**Comment by Tekuzo** [comment]
I’m sure I’ll be ok, I got the first version of your plug-in working without a video. I’ll touch back after I have worked on this for a bit.

**Comment by Tekuzo** [comment]
Is there a new version of the of the GDIP file, and a admob sdk to download with this? or is it using the same GDIP files, and the same aar and gdap on android?

Will the existing sdk still work?

**Comment by gumaciel** [comment]
@Tekuzo you need to download everything again, the SDK was changed

**Comment by gumaciel** [comment]
Soon I will create a versioning of the Android and iOS Plugin, will be three repositories:

1. AdMob Editor Plugin
2. AdMob Android Plugin
3. AdMob iOS Plugin

**Comment by Tekuzo** [comment]
No matter what I do, it just says that ads are not loading

![Screen Shot 2021-06-26 at 1 11 24 PM](https://user-images.githubusercontent.com/6944363/123520726-0bf9a480-d680-11eb-8c79-ca94b1252b61.png)

**Comment by Tekuzo** [comment]
I have tried both allowing the app to track and not
I have changed the rating
nothing seems to be helping.

**Comment by Tekuzo** [comment]
Well, your test room worked
so it must be something I am doing wrong

**Comment by Tekuzo** [comment]
> Soon I will create a versioning of the Android and iOS Plugin, will be three repositories:
> 
>     1. AdMob Editor Plugin
> 
>     2. AdMob Android Plugin
> 
>     3. AdMob iOS Plugin

It works in your test room, and it works when I have the test Ad IDs

When I switch the test Ad IDs in the plugin interface for my Ad ID, it stops working and fails to load ads.

**Comment by Tekuzo** [comment]
@gumaciel 

I seem to have run into a problem. I have updated the plugin on iOS and Android. I am currently trying to test my app on iOS.

The app works just fine if I leave the ids alone but if I update the GADApplicationIdentifier inside of xcode and update the unit Id in the plugin, it stops working
![IMG_0191](https://user-images.githubusercontent.com/6944363/123523998-7ec14a80-d695-11eb-99d7-39599ec10a6f.PNG)


`2021-06-26 15:39:47.658492-0400 Captain Skyrunner[2536:1120872] [connection] nw_endpoint_handler_set_adaptive_read_handler [C1.1.1 xxx.xxx.xxx.x:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for read_timeout failed`
`2021-06-26 15:39:47.658553-0400 Captain Skyrunner[2536:1120872] [connection] nw_endpoint_handler_set_adaptive_write_handler [C1.1.1 xxx.xxx.xxx.x:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for write_timeout failed`
`2021-06-26 15:39:47.826002-0400 Captain Skyrunner[2536:1120383] Rewarded ad failed to load with error: Request Error: No ad to show.`
`2021-06-26 15:39:47.826045-0400 Captain Skyrunner[2536:1120383] error while creating reward`

**Comment by Tekuzo** [comment]
If I close my app and reload it, then rewarded ads load.
Rewarded ads fail to load the first time my game is launched after a clean install it seems. I am going to do some more experimenting. I am not sure what I am doing differently than your example room.

**Comment by gumaciel** [comment]
This happen Everytime? I am not home right now, when I come home I will test

**Comment by Tekuzo** [comment]
Yes, every time on first launch it will not play an ad from my app id

I just tested on android and everything seems to work just fine.

**Comment by Tekuzo** [comment]
The new version seems to not be prompting me with the track / not track prompt either.

**Comment by Tekuzo** [comment]
Ok, I have done a little bit more testing. When I update the info.plst to have my GADApplicationIdentifier from Admob, and update the rewarded Ad ID inside of the plugin configuration screen

Rewards Ads are not loading when my Phone is on Wifi, they only load when I am on LTE.
Rewarded Ads are also not loading when I select the app to not track me. The console always says "ad failed to load, no ad to serve".

If I leave info.plst alone, and leave the Ad IDs at the default values the test ads seem to load fine regardless of my responses. I am not sure what the exact nature of the problem is, if its is a problem with the plugin or if there are actually no ads to serve.

**Comment by gumaciel** [comment]
@Tekuzo Hi, we tested here and it's working normally: 

https://user-images.githubusercontent.com/20030153/124389081-f9085500-dcbb-11eb-992a-654893735f1f.mov


Rewarded Unit Id: `ca-app-pub-3940256099942544/1712485313`
GADApplicationIdentifier: `ca-app-pub-3940256099942544~1458002511`

**Comment by Tekuzo** [comment]
I will try this and respond with an update in a little bit.

If these work fine, then perhaps there just isn't an ad to serve with my Unit ID and App Identifier?

**Comment by gumaciel** [comment]
@Tekuzo yes, to ads appear with your Unit ID and App Identifier, please read it: https://support.google.com/admob/answer/9469204?hl=en

`New iOS apps will not show Google ads until they’re listed in the Apple App Store`

**Comment by Tekuzo** [comment]
Ok, so this has been a me problem the while time.

Excellent, thank you for that bit of missing information.

Your plugin is fantastic then :D and I have been having no issues.
