### ISSUE TITLE
[FEATURE] Add Adaptive Banner Size to Android and iOS

### ISSUE THREAD

**Issue by gumaciel** [Poing-Studios/Godot-AdMob-Android-iOS#86]
**Is your feature request related to a problem? Please describe.**
Smart Banner is deprecated and soon will be removed in favor of adaptive banner: https://developers.google.com/admob/android/banner/adaptive

https://github.com/Poing-Studios/Godot-AdMob-Android-iOS/discussions/84

**Comment by gumaciel** [comment]
https://user-images.githubusercontent.com/20030153/123034546-17b74380-d3c0-11eb-9113-5e8a1f715476.mov

@kyoz Check it out, also working for Android on the same way, soon i will publish the update.

**Comment by kyoz** [comment]
@gumaciel yay, it's so cool. I'll test it as soon as new public come

**Comment by gumaciel** [comment]
@kyoz please test it out,

i notice the values of Plugin are not changing when install on the app, maybe is due the "config.json" file is located on "user://" folder, i will check it out tomorrow
![Captura de Tela 2021-06-23 às 01 39 48](https://user-images.githubusercontent.com/20030153/123036736-e6d90d80-d3c3-11eb-9e0e-703a23f7a5a3.png)

**Comment by kyoz** [comment]
@gumaciel Yeah, as you said the config is not saved.  i'll to config it directly in the code. But the Adaptive Ad work perfectly. Thank you very much :smile:

**Comment by gumaciel** [comment]
@kyoz new version of Editor Plugin released: https://github.com/Poing-Studios/Godot-AdMob-Editor-Plugin/releases/tag/0.2.2

I will close this issue since was complete, thank you!

**Comment by gumaciel** [comment]
@kyoz 0.3.0 is released, please watch this video: https://youtu.be/mmZZj0kC7Jk

It's for Android, but you will still need to do the same for iOS here: 
![Captura de Tela 2021-06-26 às 00 39 04](https://user-images.githubusercontent.com/20030153/123500788-ebe1cb00-d616-11eb-9d2b-9cbfc9ac9495.png)

I can't create a good video right now, there's just me working on this plugin, and it's a lot of work :( but in a few days a well explained video will come out

Ps: It fixes the config file is not saving when export

**Comment by kyoz** [comment]
@gumaciel Thank you very much for your hard work. I'm testing it all out, but it's seem everything is ok now, i'll publish an app soon and checked if everything is correct. :cat:

**Comment by kyoz** [comment]
@gumaciel Everything is ok for now, i'v tested everything. Soon i'll release my mini game to test the isReal flag, if there are any problem i'll open an issue, thank you very much :smile:

**Comment by gumaciel** [comment]
Thank you!

**Comment by gumaciel** [comment]
I discovered a bug with adaptive banner: It's not working on Landscape

https://www.gitmemory.com/issue/googleads/googleads-mobile-unity/1068/622344487

**Comment by kyoz** [comment]
Yeah, i'v see this in the past too. Admob have some rule to display ads. This error is usually by the height of admob is to big, compare to screen height.

This is my first time to try a game engine so i don't know much, but i'v worked with some mobile framework like ionic and react native and use their admob plugin. Usually, the ad is display inside a wrapper div. The position doesn't matter, ads will try to fill in that wrapper. It's like we can set min and max height (width) for the banner and admob will try to fill it.
